backend:
  name: github
  repo: remarkable-lab/claukishin

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: public, label: Public, widget: "boolean", default: false }
      - { name: tags, label: Tags, widget: "list", default: ["finanzas"] }
      - { name: body, label: Body, widget: markdown }
